[project]
name = "space"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.116.0",
    "ruff>=0.12.2",
    "uvicorn>=0.35.0",
]
